name: Scrape
# Controls when the action will run.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    
jobs: 
  autoscrape:
    runs-on: [windows-latest]
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      
      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2
        
      - name: Install Packages
        run: |
          R 'install.packages("tidyverse", type = "win.binary")' 
          R 'install.packages("rvest", type = "win.binary")' 
          R 'install.packages("janitor", type = "win.binary")' 
          R 'install.packages("mailR", type = "win.binary")'
          R 'install.packages("rmarkdown", type = "win.binary")' 
          R 'install.packages("pandocs", type = "win.binary")' 
        shell: Rscript {0}
          
      - name: Run Scraper
        run: Rscript aaa_gas_scraper_GITHUB.R
       
      - name: Add and commit	
        run: |
          git add .	
          git config user.name "Automated"	
          git config user.email "actions@users.noreply.github.com"	
          git commit -m "Latest data" 	
      - name: Push	
        run: git push
      
